spring.application.name=test-online-judge
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.submission-topic=submissions
app.test.timeout-ms=30000
app.test.interval-ms=300000
app.test.initial-delay-ms=10000
