spring.application.name=online-judge
rivalcode.service.name=online-judge
rivalcode.service.version=0.0.1-SNAPSHOT

# Kafka Config
app.kafka.submission-topic=submissions
app.kafka.result-topic=submission-results
spring.kafka.bootstrap-servers=localhost:9092

# Sandbox Config
app.sandbox.java-path=/usr/bin/java
app.sandbox.max-boxes=100
app.sandbox.default-wall-time-multiplier=2.0
app.sandbox.default-time-limit-ms=2000
app.sandbox.default-memory-limit-kb=65536
app.sandbox.default-output-limit-bytes=1048576
app.sandbox.compile-time-limit-ms=30000
app.sandbox.compile-memory-limit-kb=4194304
app.sandbox.compile-output-limit-bytes=67108864
app.sandbox.custom-checker-time-limit-ms=2000
app.sandbox.custom-checker-memory-limit-kb=65536
app.sandbox.custom-checker-output-limit-bytes=65536

# Logging
logging.level.com.rivalcode.onlinejudge.service.impl.IsolateSandbox=DEBUG
