spring.application.name=online-judge

# Kafka Config
app.kafka.submission-topic=submissions
spring.kafka.bootstrap-servers=localhost:9092

# Sandbox Config
app.sandbox.java-path=/usr/bin/java
app.sandbox.max-boxes=1000
app.sandbox.default-wall-time-multiplier=2.0

# Logging
logging.level.com.vinogradov.onlinejudge.service.impl.IsolateSandbox=DEBUG
