spring.application.name=online-judge
rivalcode.service.name=online-judge
rivalcode.service.version=0.0.1-SNAPSHOT

# Kafka Config
app.kafka.submission-topic=submissions
spring.kafka.bootstrap-servers=localhost:9092

# Sandbox Config
app.sandbox.java-path=/usr/bin/java
app.sandbox.max-boxes=1000
app.sandbox.default-wall-time-multiplier=2.0
app.sandbox.default-time-limit-ms=2000
app.sandbox.default-memory-limit-kb=65536

# Logging
logging.level.com.rivalcode.onlinejudge.service.impl.IsolateSandbox=DEBUG
